services:
  php:
    build:
      context: './php/' # Project root as context
      dockerfile: Dockerfile # Specify path to Dockerfile
    image: localhost/s753-t73-php
    #volumes:
    #  - ./public:/var/www/html/
  apache:
    build:
      context: './apache/' # Project root as context
      dockerfile: Dockerfile # Specify path to Dockerfile
    image: localhost/s753-t73-apache
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"
    #volumes:
    #  - ./public:/var/www/html/
  mysql:
    build:
      context: './mysql/' # Project root as context
      dockerfile: Dockerfile # Specify path to Dockerfile
    image: localhost/s753-t73-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      # The volume mount for dump.sql is NO LONGER NEEDED here,
      # as the dump.sql is now COPIED into the image by the Dockerfile.
      # - ./public/dump:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"
    command: --default-authentication-plugin=mysql_native_password
volumes:
    db_data: